//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedditTrafficExtreme
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProxiesLoaded
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public string Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool InUse { get; set; }
        public Nullable<System.DateTime> NextUse { get; set; }
    }
}
